apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: {{ include "spam2000.fullname" . }}  
  labels:  
    app: {{ include "spam2000.name" . }}  
    app.kubernetes.io/name: {{ include "spam2000.name" . }}  
spec:  
  replicas: {{ .Values.replicaCount }}  
  selector:  
    matchLabels:  
      app.kubernetes.io/name: {{ include "spam2000.name" . }}  
  template:  
    metadata:  
      labels:  
        app.kubernetes.io/name: {{ include "spam2000.name" . }}  
    spec:  
      containers:  
        - name: spam2000  
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
          imagePullPolicy: {{ .Values.image.pullPolicy }}  
          ports:  
            - name: http  
              containerPort: {{ .Values.service.port }}  
          # якщо додаток потребує env/args — додати сюди  
