apiVersion: monitoring.coreos.com/v1  
kind: ServiceMonitor  
metadata:  
  name: {{ include "spam2000.fullname" . }}  
  labels:  
    release: vm-k8s-stack  
spec:  
  selector:  
    matchLabels:  
      app.kubernetes.io/name: {{ include "spam2000.name" . }}  
  endpoints:  
    - port: http  
      path: /metrics  
      interval: 15s  
