apiVersion: v1  
kind: Service  
metadata:  
  name: {{ include "spam2000.fullname" . }}  
  labels:  
    app.kubernetes.io/name: {{ include "spam2000.name" . }}  
spec:  
  type: {{ .Values.service.type }}  
  selector:  
    app.kubernetes.io/name: {{ include "spam2000.name" . }}  
  ports:  
    - name: http-metrics  
      port: {{ .Values.service.port }}  
      targetPort: {{ .Values.service.port }}  
